baseurl: https://jonathanwarden.com/
languageCode: en-us
theme: hugo-theme-stack
# theme: luizdepra/hugo-coder
paginate: 20
# title: Jonathan Warden
title: Jonathan Warden's Blog

# languages:
#     en:
#         languageName: English
#         # title: The Writings of Jonathan Warden
#         description: Example description
#         weight: 1

# Change it to your Disqus shortname before using
disqusShortname: todo

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

taxonomies:
  # category: categories
  tag: tags
  series: series

permalinks:
    philosophy: /:slug/
    travel: /:slug/
    language-design: /:slug/
    social-protocols: /:slug/
    theory: /:slug/
    # page: /:slug/

params:
    mainSections:
        - social-protocols
        - philosophy
        - travel
        - theory
        - language-design
    featuredImageField: image
    rssFullContent: true
    favicon:  # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    footer:
        since: 2016
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        # emoji: 🍥
        # subtitle: Philosophical Engineer
        avatar: 
            enabled: false
        # logo:
        #     enabled: true
        #     local: true

    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false 
      
    widgets:
        homepage:
            - type: search
            # - type: archives
            #   params:
            #       limit: 5
            # - type: categories
            #   params:
            #       limit: 10
        page:
            - type: series
            - type: toc


    opengraph:
        twitter:
            # Your Twitter username
            site: johnwarden

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:


    # social:
    #     - identifier: github
    #       name: GitHub
    #       url: https://github.com/johnwarden
    #       weight: 1
    #       params:
    #           icon: brand-github

    #     - identifier: twitter
    #       name: Twitter
    #       weight: 2
    #       url: https://twitter.com/johnwarden
    #       params:
    #           icon: brand-twitter

    #     - identifier: linkedin
    #       weight: 3
    #       name: LinkedIn
    #       url: https://www.linkedin.com/in/jonathan-r-warden-4aa2357/
    #       params:
    #           icon: brand-linkedin


enableInlineShortcodes: true

navigateToChanged: true

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

module:
  mounts:
  - source: content
    target: content
  - source: content/social-protocols
    target: content/social-protocols
  - source: syndication-sources/social-protocols/content/articles/deliberative-consensus-protocols
    target: content/social-protocols/deliberative-consensus-protocols
  - source: syndication-sources/social-protocols/content/articles/give-truth-the-advantage
    target: content/social-protocols/give-truth-the-advantage
  - source: syndication-sources/social-protocols/content/articles/the-deliberative-poll
    target: content/social-protocols/the-deliberative-poll
  - source: syndication-sources/social-protocols/content/articles/the-law-of-attention
    target: content/social-protocols/the-law-of-attention
  - source: syndication-sources/social-protocols/content/articles/truthtelling-games
    target: content/social-protocols/truthtelling-games
  - source: syndication-sources/social-protocols/content/articles/what-deserves-our-attention
    target: content/social-protocols/what-deserves-our-attention
